//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Logic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +13
        ///-12
        ///-14
        ///+19
        ///-13
        ///+16
        ///+12
        ///+19
        ///+8
        ///-10
        ///-9
        ///-2
        ///+1
        ///-13
        ///+10
        ///-7
        ///-11
        ///-10
        ///+1
        ///-14
        ///-15
        ///+16
        ///+6
        ///+17
        ///-19
        ///-13
        ///+5
        ///-19
        ///-12
        ///-10
        ///-12
        ///+13
        ///+14
        ///+3
        ///-13
        ///+3
        ///+17
        ///+10
        ///-16
        ///+19
        ///+1
        ///+11
        ///-16
        ///+3
        ///-16
        ///-12
        ///-7
        ///-11
        ///-6
        ///-19
        ///+6
        ///+12
        ///+15
        ///-7
        ///-18
        ///+13
        ///-4
        ///-14
        ///-7
        ///-18
        ///+17
        ///+9
        ///-12
        ///-3
        ///-13
        ///-16
        ///+14
        ///-4
        ///-12
        ///-10
        ///-3
        ///+8
        ///-10
        ///-4
        ///-10
        ///-11
        ///-14
        ///+11
        ///-7
        ///+17
        ///+19
        ///+2
        ///-13
        ///+17
        ///-10
        ///-6
        ///+15
        ///+7
        ///+15
        ///-3
        ///-7
        ///-6
        ///-1
        ///-13
        ///-5
        ///-6
        ///-6
        ///-12
        ///-18
        ///-7
        ///-19
        ///-5
        ///-15
        ///-7
        ///+4
        ///-18
        ///+5
        ///+17
        ///-2
        ///-12
        ///-1        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uosnxmfkezbojfdgwvrtaqhluy
        ///iosnxmfkazbcopdgnvrtaqhluy
        ///ioanxmfkezbcjpdgwvrjaohluy
        ///uosnxmfkezbcjpjgwvrtaqhlut
        ///imsnxmfkezbcjpugwvataqhluy
        ///ioenxmfkezbcjpdgwvrraqhluz
        ///iosnxmfkezbcjpdgevitnqhluy
        ///iosnxmfkezcccpdgcvrtaqhluy
        ///loinxmfkezbcjpdgwvrtaqhluu
        ///iosnlmfkezbczndgwvrtaqhluy
        ///iosnxmfkezbcjpdgwvrifghluy
        ///iosnuhfkezbcjpugwvrtaqhluy
        ///iosnxmfkezbcwpdgwvrtaihlgy
        ///iosnxzfwuzbcjpdgwvrtaqhluy
        ///hosnxmfjizbcjpdgwvrtaqhluy
        ///iornxmfktzbcjpdgwvrtaqhluo
        ///nosnxmfkdzbcjpdgwvrtaqhlwy
        ///iosnxmfkezbcjpdgwvrtaktluq
        ///ioszxmlk [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1 @ 35,93: 11x13
        ///#2 @ 518,811: 15x18
        ///#3 @ 335,512: 11x10
        ///#4 @ 635,155: 14x24
        ///#5 @ 919,43: 10x16
        ///#6 @ 391,695: 14x16
        ///#7 @ 635,372: 17x17
        ///#8 @ 289,489: 19x29
        ///#9 @ 695,413: 10x25
        ///#10 @ 730,730: 27x11
        ///#11 @ 680,761: 29x22
        ///#12 @ 44,685: 18x23
        ///#13 @ 71,613: 28x16
        ///#14 @ 292,456: 22x17
        ///#15 @ 16,950: 14x10
        ///#16 @ 778,140: 27x23
        ///#17 @ 448,425: 22x22
        ///#18 @ 681,770: 28x21
        ///#19 @ 19,172: 23x21
        ///#20 @ 542,333: 17x18
        ///#21 @ 12,919: 14x20
        ///#22 @ 466,752: 28x14
        ///#23 @ 700,661: 18x21
        ///#24 @ 582,738: 29x24
        ///# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1 @ 1,3: 4x4
        ///#2 @ 3,1: 4x4
        ///#3 @ 5,5: 2x2.
        /// </summary>
        internal static string Day3Example {
            get {
                return ResourceManager.GetString("Day3Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1518-05-30 00:04] Guard #2417 begins shift
        ///[1518-10-20 00:48] wakes up
        ///[1518-08-12 00:14] falls asleep
        ///[1518-05-09 23:54] Guard #2969 begins shift
        ///[1518-07-28 00:14] falls asleep
        ///[1518-09-06 23:57] Guard #797 begins shift
        ///[1518-05-14 00:54] wakes up
        ///[1518-08-24 00:45] falls asleep
        ///[1518-09-26 00:47] falls asleep
        ///[1518-02-18 23:58] Guard #521 begins shift
        ///[1518-06-15 00:58] wakes up
        ///[1518-03-02 00:19] falls asleep
        ///[1518-03-21 00:00] Guard #521 begins shift
        ///[1518-02-26 00:40] wakes up
        ///[1518-04- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1518-11-01 00:00] Guard #10 begins shift
        ///[1518-11-01 00:05] falls asleep
        ///[1518-11-01 00:25] wakes up
        ///[1518-11-01 00:30] falls asleep
        ///[1518-11-01 00:55] wakes up
        ///[1518-11-01 23:58] Guard #99 begins shift
        ///[1518-11-02 00:40] falls asleep
        ///[1518-11-02 00:50] wakes up
        ///[1518-11-03 00:05] Guard #10 begins shift
        ///[1518-11-03 00:24] falls asleep
        ///[1518-11-03 00:29] wakes up
        ///[1518-11-04 00:02] Guard #99 begins shift
        ///[1518-11-04 00:36] falls asleep
        ///[1518-11-04 00:46] wakes up
        ///[1518-11-05 00:03] Guard #99 b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4Example {
            get {
                return ResourceManager.GetString("Day4Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OoibdgGDEesYySsSMmlLIKkkVvKvViERxXVvrfmMsSFeaAvnNVdMmJjDBmMXbBJjWwPZzpHhLlCsSfFpPcKVvxlLXbBkxUIJjfFoOigEeGHhdDJjdDAazTtrRCotTFfOoOcZPDejJEdpTzsSYzZMmyMmZtshHJzZkKYyJjnAaNjpflLFPUuNndnPpNxAiIMbBCcgLlGPrRpmaHnNhXDoOzZxXUdjJWwilLIDutWwTjwMmWcCJvVxXthHfFkKdDWwmMHjbBKkRrXxlLJhOoTYytKZzrGvVgabbBBjJpPAKMmsSktwWfFTWoOwdDWpPRrPoOpBFfbOonZzNZzrRiWwIhHwrlLRZAKkNntAazzZZYykPfFppjWwJPKWwTWVvwwWCckKuUPpcVBbbBvVmMvxXwWKkMmaAKkZzQqOoJjTttTzZNnlrPkKpRrRRrLCxXeOoXYeeEELliIyxEajJwKkIiFmMfvisSIEeZzPpAaSsVGNkKqOoQiInAaHhAEeIaiI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day5 {
            get {
                return ResourceManager.GetString("Day5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dabAcCaCBAcCcaDA.
        /// </summary>
        internal static string Day5Example {
            get {
                return ResourceManager.GetString("Day5Example", resourceCulture);
            }
        }
    }
}
