//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic.Properties
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Logic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }


        internal static string Day1
        {
            get
            {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to uosnxmfkezbojfdgwvrtaqhluy
        ///iosnxmfkazbcopdgnvrtaqhluy
        ///ioanxmfkezbcjpdgwvrjaohluy
        ///uosnxmfkezbcjpjgwvrtaqhlut
        ///imsnxmfkezbcjpugwvataqhluy
        ///ioenxmfkezbcjpdgwvrraqhluz
        ///iosnxmfkezbcjpdgevitnqhluy
        ///iosnxmfkezcccpdgcvrtaqhluy
        ///loinxmfkezbcjpdgwvrtaqhluu
        ///iosnlmfkezbczndgwvrtaqhluy
        ///iosnxmfkezbcjpdgwvrifghluy
        ///iosnuhfkezbcjpugwvrtaqhluy
        ///iosnxmfkezbcwpdgwvrtaihlgy
        ///iosnxzfwuzbcjpdgwvrtaqhluy
        ///hosnxmfjizbcjpdgwvrtaqhluy
        ///iornxmfktzbcjpdgwvrtaqhluo
        ///nosnxmfkdzbcjpdgwvrtaqhlwy
        ///iosnxmfkezbcjpdgwvrtaktluq
        ///ioszxmlk [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2
        {
            get
            {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #1 @ 35,93: 11x13
        ///#2 @ 518,811: 15x18
        ///#3 @ 335,512: 11x10
        ///#4 @ 635,155: 14x24
        ///#5 @ 919,43: 10x16
        ///#6 @ 391,695: 14x16
        ///#7 @ 635,372: 17x17
        ///#8 @ 289,489: 19x29
        ///#9 @ 695,413: 10x25
        ///#10 @ 730,730: 27x11
        ///#11 @ 680,761: 29x22
        ///#12 @ 44,685: 18x23
        ///#13 @ 71,613: 28x16
        ///#14 @ 292,456: 22x17
        ///#15 @ 16,950: 14x10
        ///#16 @ 778,140: 27x23
        ///#17 @ 448,425: 22x22
        ///#18 @ 681,770: 28x21
        ///#19 @ 19,172: 23x21
        ///#20 @ 542,333: 17x18
        ///#21 @ 12,919: 14x20
        ///#22 @ 466,752: 28x14
        ///#23 @ 700,661: 18x21
        ///#24 @ 582,738: 29x24
        ///# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3
        {
            get
            {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #1 @ 1,3: 4x4
        ///#2 @ 3,1: 4x4
        ///#3 @ 5,5: 2x2.
        /// </summary>
        internal static string Day3Example
        {
            get
            {
                return ResourceManager.GetString("Day3Example", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [1518-05-30 00:04] Guard #2417 begins shift
        ///[1518-10-20 00:48] wakes up
        ///[1518-08-12 00:14] falls asleep
        ///[1518-05-09 23:54] Guard #2969 begins shift
        ///[1518-07-28 00:14] falls asleep
        ///[1518-09-06 23:57] Guard #797 begins shift
        ///[1518-05-14 00:54] wakes up
        ///[1518-08-24 00:45] falls asleep
        ///[1518-09-26 00:47] falls asleep
        ///[1518-02-18 23:58] Guard #521 begins shift
        ///[1518-06-15 00:58] wakes up
        ///[1518-03-02 00:19] falls asleep
        ///[1518-03-21 00:00] Guard #521 begins shift
        ///[1518-02-26 00:40] wakes up
        ///[1518-04- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4
        {
            get
            {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [1518-11-01 00:00] Guard #10 begins shift
        ///[1518-11-01 00:05] falls asleep
        ///[1518-11-01 00:25] wakes up
        ///[1518-11-01 00:30] falls asleep
        ///[1518-11-01 00:55] wakes up
        ///[1518-11-01 23:58] Guard #99 begins shift
        ///[1518-11-02 00:40] falls asleep
        ///[1518-11-02 00:50] wakes up
        ///[1518-11-03 00:05] Guard #10 begins shift
        ///[1518-11-03 00:24] falls asleep
        ///[1518-11-03 00:29] wakes up
        ///[1518-11-04 00:02] Guard #99 begins shift
        ///[1518-11-04 00:36] falls asleep
        ///[1518-11-04 00:46] wakes up
        ///[1518-11-05 00:03] Guard #99 b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4Example
        {
            get
            {
                return ResourceManager.GetString("Day4Example", resourceCulture);
            }
        }

        internal static string Day5
        {
            get
            {
                return ResourceManager.GetString("Day5", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to dabAcCaCBAcCcaDA.
        /// </summary>
        internal static string Day5Example
        {
            get
            {
                return ResourceManager.GetString("Day5Example", resourceCulture);
            }
        }


        internal static string Day6
        {
            get
            {
                return ResourceManager.GetString("Day6", resourceCulture);
            }
        }

        internal static string Day6Example
        {
            get
            {
                return ResourceManager.GetString("Day6Example", resourceCulture);
            }
        }


        internal static string Day7
        {
            get
            {
                return ResourceManager.GetString("Day7", resourceCulture);
            }
        }

        internal static string Day7Example
        {
            get
            {
                return ResourceManager.GetString("Day7Example", resourceCulture);
            }
        }

        internal static string Day8
        {
            get
            {
                return ResourceManager.GetString("Day8", resourceCulture);
            }
        }

        internal static string Day8Example
        {
            get
            {
                return ResourceManager.GetString("Day8Example", resourceCulture);
            }
        }

        internal static string Day9
        {
            get
            {
                return ResourceManager.GetString("Day9", resourceCulture);
            }
        }

        internal static string Day9Example
        {
            get
            {
                return ResourceManager.GetString("Day9Example", resourceCulture);
            }
        }

        internal static string Day10
        {
            get
            {
                return ResourceManager.GetString("Day10", resourceCulture);
            }
        }

        internal static string Day10Example
        {
            get
            {
                return ResourceManager.GetString("Day10Example", resourceCulture);
            }
        }

        internal static string Day11
        {
            get
            {
                return ResourceManager.GetString("Day11", resourceCulture);
            }
        }

        internal static string Day11Example
        {
            get
            {
                return ResourceManager.GetString("Day11Example", resourceCulture);
            }
        }

        internal static string Day12
        {
            get
            {
                return ResourceManager.GetString("Day12", resourceCulture);
            }
        }

        internal static string Day12Example
        {
            get
            {
                return ResourceManager.GetString("Day12Example", resourceCulture);
            }
        }
        internal static string Day13
        {
            get
            {
                return ResourceManager.GetString("Day13", resourceCulture);
            }
        }

        internal static string Day13Example
        {
            get
            {
                return ResourceManager.GetString("Day13Example", resourceCulture);
            }
        }

        internal static string Day14
        {
            get
            {
                return ResourceManager.GetString("Day14", resourceCulture);
            }
        }

        internal static string Day14Example
        {
            get
            {
                return ResourceManager.GetString("Day14Example", resourceCulture);
            }
        }

        internal static string Day15
        {
            get
            {
                return ResourceManager.GetString("Day15", resourceCulture);
            }
        }

        internal static string Day15Example
        {
            get
            {
                return ResourceManager.GetString("Day15Example", resourceCulture);
            }
        }





        internal static string Day16
        {
            get
            {
                return ResourceManager.GetString("Day16", resourceCulture);
            }
        }

        internal static string Day16Example
        {
            get
            {
                return ResourceManager.GetString("Day16Example", resourceCulture);
            }
        }



        internal static string Day17
        {
            get
            {
                return ResourceManager.GetString("Day17", resourceCulture);
            }
        }

        internal static string Day17Example
        {
            get
            {
                return ResourceManager.GetString("Day17Example", resourceCulture);
            }
        }



        internal static string Day18
        {
            get
            {
                return ResourceManager.GetString("Day18", resourceCulture);
            }
        }

        internal static string Day18Example
        {
            get
            {
                return ResourceManager.GetString("Day18Example", resourceCulture);
            }
        }



        internal static string Day19
        {
            get
            {
                return ResourceManager.GetString("Day19", resourceCulture);
            }
        }

        internal static string Day19Example
        {
            get
            {
                return ResourceManager.GetString("Day19Example", resourceCulture);
            }
        }




        internal static string Day20
        {
            get
            {
                return ResourceManager.GetString("Day20", resourceCulture);
            }
        }

        internal static string Day20Example
        {
            get
            {
                return ResourceManager.GetString("Day20Example", resourceCulture);
            }
        }




        internal static string Day21
        {
            get
            {
                return ResourceManager.GetString("Day21", resourceCulture);
            }
        }

        internal static string Day21Example
        {
            get
            {
                return ResourceManager.GetString("Day21Example", resourceCulture);
            }
        }



        internal static string Day22
        {
            get
            {
                return ResourceManager.GetString("Day22", resourceCulture);
            }
        }

        internal static string Day22Example
        {
            get
            {
                return ResourceManager.GetString("Day22Example", resourceCulture);
            }
        }




        internal static string Day23
        {
            get
            {
                return ResourceManager.GetString("Day23", resourceCulture);
            }
        }

        internal static string Day23Example
        {
            get
            {
                return ResourceManager.GetString("Day23Example", resourceCulture);
            }
        }




        internal static string Day24
        {
            get
            {
                return ResourceManager.GetString("Day24", resourceCulture);
            }
        }

        internal static string Day24Example
        {
            get
            {
                return ResourceManager.GetString("Day24Example", resourceCulture);
            }
        }




        internal static string Day25
        {
            get
            {
                return ResourceManager.GetString("Day25", resourceCulture);
            }
        }

        internal static string Day25Example
        {
            get
            {
                return ResourceManager.GetString("Day25Example", resourceCulture);
            }
        }




        internal static string Day26
        {
            get
            {
                return ResourceManager.GetString("Day26", resourceCulture);
            }
        }

        internal static string Day26Example
        {
            get
            {
                return ResourceManager.GetString("Day26Example", resourceCulture);
            }
        }


    }

}
