//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventCode.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventCode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 88,88,211,106,141,1,78,254,2,111,77,255,90,0,54,205.
        /// </summary>
        internal static string dag10_2017 {
            get {
                return ResourceManager.GetString("dag10_2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s,se,ne,ne,ne,ne,ne,ne,ne,n,sw,sw,nw,sw,n,nw,nw,sw,nw,nw,nw,nw,sw,nw,nw,nw,nw,s,nw,nw,sw,nw,sw,sw,sw,nw,sw,sw,sw,sw,sw,sw,sw,s,sw,sw,sw,sw,se,sw,s,s,sw,s,ne,nw,nw,s,n,s,sw,s,sw,nw,se,s,s,s,s,s,nw,s,nw,s,s,se,se,se,se,se,se,s,se,s,s,se,ne,se,se,se,se,se,ne,ne,se,se,se,se,se,ne,se,se,se,sw,sw,se,ne,s,ne,se,sw,n,sw,ne,ne,se,se,ne,se,ne,se,se,se,se,sw,ne,se,se,ne,se,sw,se,ne,se,ne,s,ne,ne,ne,ne,s,se,ne,ne,ne,s,ne,nw,ne,s,ne,ne,s,ne,ne,ne,ne,ne,ne,ne,ne,ne,ne,n,ne,ne,ne,n,n,se,ne,ne,ne,ne,n,ne,ne,n,nw,ne,sw,ne,n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dag11_2017 {
            get {
                return ResourceManager.GetString("dag11_2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0: 5
        ///1: 2
        ///2: 3
        ///4: 4
        ///6: 6
        ///8: 4
        ///10: 8
        ///12: 6
        ///14: 6
        ///16: 8
        ///18: 6
        ///20: 9
        ///22: 8
        ///24: 10
        ///26: 8
        ///28: 8
        ///30: 12
        ///32: 8
        ///34: 12
        ///36: 10
        ///38: 12
        ///40: 12
        ///42: 12
        ///44: 12
        ///46: 12
        ///48: 14
        ///50: 12
        ///52: 14
        ///54: 12
        ///56: 14
        ///58: 12
        ///60: 14
        ///62: 14
        ///64: 14
        ///66: 14
        ///68: 14
        ///70: 14
        ///72: 14
        ///76: 14
        ///80: 18
        ///84: 14
        ///90: 18
        ///92: 17.
        /// </summary>
        internal static string dag13_2017 {
            get {
                return ResourceManager.GetString("dag13_2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0: 3
        ///1: 2
        ///4: 4
        ///6: 4.
        /// </summary>
        internal static string dag13_2017_test {
            get {
                return ResourceManager.GetString("dag13_2017_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vbqugkhl.
        /// </summary>
        internal static string dag14_2017 {
            get {
                return ResourceManager.GetString("dag14_2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x5/11,s12,x10/4,pi/d,x11/0,s6,x14/3,pa/b,x6/13,pk/m,x3/9,s12,pg/d,x14/7,pi/b,x13/15,s5,x1/8,s3,x11/6,s6,x9/2,s13,x1/3,pj/a,x13/12,s6,x9/15,s1,x7/0,s1,x11/10,s6,x3/0,s6,x9/8,pl/k,x12/13,pb/n,x15/7,pg/l,x0/11,s12,x12/10,s11,x6/9,po/i,x8/3,pk/l,s2,x14/2,s15,x6/12,pj/p,x7/14,pb/f,x3/15,ph/l,x11/1,s9,pg/o,s9,x8/2,ph/l,s15,x14/0,s1,x13/6,pj/g,x14/7,s7,pi/o,x1/12,pm/a,x13/14,s12,x4/8,pp/c,x13/14,pb/a,x0/7,s4,x5/11,s12,x1/4,s11,x6/10,pi/h,x2/8,s14,x12/3,s12,x11/7,s15,x0/13,pk/a,x11/6,s15,x8/0,s8,x7/5,s10,x9/12,s15, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dag16_2017 {
            get {
                return ResourceManager.GetString("dag16_2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set i 31
        ///set a 1
        ///mul p 17
        ///jgz p p
        ///mul a 2
        ///add i -1
        ///jgz i -2
        ///add a -1
        ///set i 127
        ///set p 618
        ///mul p 8505
        ///mod p a
        ///mul p 129749
        ///add p 12345
        ///mod p a
        ///set b p
        ///mod b 10000
        ///snd b
        ///add i -1
        ///jgz i -9
        ///jgz a 3
        ///rcv b
        ///jgz b -1
        ///set f 0
        ///set i 126
        ///rcv a
        ///rcv b
        ///set p a
        ///mul p -1
        ///add p b
        ///jgz p 4
        ///snd a
        ///set a b
        ///jgz 1 3
        ///snd b
        ///set f 1
        ///add i -1
        ///jgz i -11
        ///snd a
        ///jgz f -16
        ///jgz a -19.
        /// </summary>
        internal static string dag18_2017 {
            get {
                return ResourceManager.GetString("dag18_2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to snd 1
        ///snd 2
        ///snd p
        ///rcv a
        ///rcv b
        ///rcv c
        ///rcv d.
        /// </summary>
        internal static string dag18_2017_sendReceive_test {
            get {
                return ResourceManager.GetString("dag18_2017_sendReceive_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set a 1
        ///add a 2
        ///mul a a
        ///mod a 5
        ///snd a
        ///set a 0
        ///rcv a
        ///jgz a -1
        ///set a 1
        ///jgz a -2.
        /// </summary>
        internal static string dag18_2017_test {
            get {
                return ResourceManager.GetString("dag18_2017_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../.. =&gt; .#./###/##.
        ///#./.. =&gt; ..#/.#./#.#
        ///##/.. =&gt; ###/#../...
        ///.#/#. =&gt; .#./..#/##.
        ///##/#. =&gt; ..#/#.#/###
        ///##/## =&gt; .##/.##/.#.
        ///.../.../... =&gt; #.#./..##/##../###.
        ///#../.../... =&gt; .###/.##./.##./....
        ///.#./.../... =&gt; ####/..../..../.#.#
        ///##./.../... =&gt; #.../#..#/#.../###.
        ///#.#/.../... =&gt; ..##/###./..#./.#..
        ///###/.../... =&gt; #.../#.#./..#./#.#.
        ///.#./#../... =&gt; #.#./..#./.#../...#
        ///##./#../... =&gt; ###./.###/#.##/.#..
        ///..#/#../... =&gt; .##./.##./####/####
        ///#.#/#../... =&gt; ..##/.#.#/##../#.##
        ///.##/#../... =&gt; ...#/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dag21_2017 {
            get {
                return ResourceManager.GetString("dag21_2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{{{{{{{&lt;!!!&gt;!&gt;!!oiau!&gt;}}&lt;u!!!!,!!,e!!!&gt;&apos;&gt;}},{}}},{{{{},{}},{{&lt;&lt;&lt;&quot;!!!&gt;!!,,}!!!&gt;&apos;&gt;}},{&lt;!!{e&apos;a!!u!!u!!!!!oa&apos;!!u!&gt;!!eu!!!!!&gt;,&lt;!&gt;},&lt;,&gt;,&lt;}{!!u,!!!&gt;},&lt;!!!&gt;!!!&gt;&gt;}},{{&lt;!}aa!!{&apos;a!&gt;},&lt;!&gt;,&lt;!&gt;!&gt;,&lt;!u,&quot;aae!&gt;},&lt;&gt;,&lt;!!!&gt;!&gt;u,o!&gt;},&lt;!!!&gt;!!!&gt;,&lt;&quot;&lt;&apos;&gt;},{{&lt;,!&gt;},&lt;ae{&gt;},&lt;&lt;e!&gt;},&lt;a!!},}&gt;}},{{&lt;&gt;,{&lt;!!!&gt;!&gt;{!&gt;},&lt;!!!!!&gt;},&lt;!&gt;},&lt;!!!&gt;,&lt;!&gt;,&lt;!!o,&lt;,&gt;}},{&lt;{&apos;&gt;,{{&lt;&quot;{,&lt;!!!&gt;!&gt;!!!&gt;u!&gt;},&lt;ue!!!!u!!&apos;uua}!!!&gt;},&lt;&gt;}}},{&lt;&apos;e!!&gt;}}},{{{{},&lt;!&gt;},&lt;!!o&quot;&apos;!&gt;,&lt;u&quot;&lt;!!&lt;,o{&apos;a&gt;},{{}},{{},{{&lt;&apos;!!i&lt;&gt;},&lt;&quot;!!!!,!&gt;{{&gt;},{&lt;i&apos;&lt;{i&gt;}}},{{{&lt;!!o!!a!!&apos;!&gt;&apos;&gt;},&lt;eu!&gt;!}&quot;!&gt;,&lt;}i&gt;},{{&lt;!&gt;},&lt;oe!&gt;}, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dag9_2017 {
            get {
                return ResourceManager.GetString("dag9_2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 147,37,249,1,31,2,226,0,161,71,254,243,183,255,30,70.
        /// </summary>
        internal static string Tdag10_2017 {
            get {
                return ResourceManager.GetString("Tdag10_2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0: 5
        ///1: 2
        ///2: 3
        ///4: 4
        ///6: 6
        ///8: 4
        ///10: 8
        ///12: 6
        ///14: 6
        ///16: 8
        ///18: 6
        ///20: 9
        ///22: 8
        ///24: 10
        ///26: 8
        ///28: 8
        ///30: 12
        ///32: 8
        ///34: 12
        ///36: 10
        ///38: 12
        ///40: 12
        ///42: 12
        ///44: 12
        ///46: 12
        ///48: 14
        ///50: 12
        ///52: 14
        ///54: 12
        ///56: 14
        ///58: 12
        ///60: 14
        ///62: 14
        ///64: 14
        ///66: 14
        ///68: 14
        ///70: 14
        ///72: 14
        ///76: 14
        ///80: 18
        ///84: 14
        ///90: 18
        ///92: 17.
        /// </summary>
        internal static string Tdag13_2017 {
            get {
                return ResourceManager.GetString("Tdag13_2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set i 31
        ///set a 1
        ///mul p 17
        ///jgz p p
        ///mul a 2
        ///add i -1
        ///jgz i -2
        ///add a -1
        ///set i 127
        ///set p 952
        ///mul p 8505
        ///mod p a
        ///mul p 129749
        ///add p 12345
        ///mod p a
        ///set b p
        ///mod b 10000
        ///snd b
        ///add i -1
        ///jgz i -9
        ///jgz a 3
        ///rcv b
        ///jgz b -1
        ///set f 0
        ///set i 126
        ///rcv a
        ///rcv b
        ///set p a
        ///mul p -1
        ///add p b
        ///jgz p 4
        ///snd a
        ///set a b
        ///jgz 1 3
        ///snd b
        ///set f 1
        ///add i -1
        ///jgz i -11
        ///snd a
        ///jgz f -16
        ///jgz a -19.
        /// </summary>
        internal static string Tdag18_2017 {
            get {
                return ResourceManager.GetString("Tdag18_2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{{{},{{{&lt;a!!!&gt;aa!!!&gt;,,,}!&gt;!&gt;!!eo!!a&gt;},&lt;&apos;!!!&gt;,&lt;!&gt;}!!!&gt;u!&apos;!&gt;,&lt;!!!&gt;!&gt;o!!!&gt;,&lt;&apos;!!!&gt;!!!!&lt;{{i&gt;},{{}},{{&lt;i!!!&gt;u{!!eu!!&gt;}}},{{{{{&lt;&quot;!&gt;},&lt;!o!&gt;},&lt;&lt;!!!!!!,!!i&gt;},{&lt;{!&gt;},&lt;ii&apos;&gt;},{{&lt;,o!!&lt;&apos;!!&quot;!!!&gt;&gt;,{}}}}},{}},{{}}}},{{{{&lt;e!e,!a&apos;!!!&gt;}e&quot;}&gt;,{&lt;o!&gt;,&lt;{&lt;!&gt;},&lt;&lt;!&lt;&apos;!!ia&gt;}},{{},&lt;&apos;!!!&gt;!!e&lt;&quot;{u!&gt;},&lt;&lt;!!!!!}&gt;}},{{{{&lt;!!!&gt;!!!!iu!!!&gt;!!!&gt;{&lt;eu}i,!!!!!!&gt;}},{{&lt;&gt;,&lt;!!!!o!a&quot;{!&gt;},&lt;i!&gt;,&lt;!!u!!a!&gt;},&lt;&quot;!i!&gt;},&lt;}au!&gt;!!o&gt;}},{&lt;!&gt;},&lt;e}iaae&apos;}!&gt;!,!&gt;o{,e!!{!&gt;&gt;}},{&lt;&quot;&quot;!&gt;!&gt;a&gt;,{&lt;!{&apos;u!!}{u,!&gt;},&lt;!&gt;,&lt;&apos;}a&gt;}},{{},{&lt;}!!!&gt;&apos;o&gt;}}},{{{&lt;oi&apos;&lt;}!!!!&gt;},&lt;&apos;!&gt;},&lt;u!&gt;&gt;},{&lt;!!!!!!!&gt;},&lt;e!! [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tday9_2017 {
            get {
                return ResourceManager.GetString("Tday9_2017", resourceCulture);
            }
        }
    }
}
